/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Consultant, Shift, LeaveRequest } from '../types';
import { Calendar, Award, Share2, ShieldAlert } from 'lucide-react';

interface AnalyticsProps {
  currentYear: number;
  currentMonth: number; // 0-indexed
  consultants: Consultant[];
  shifts: Shift[];
  leaves: LeaveRequest[];
}

export default function Analytics({
  currentYear,
  currentMonth,
  consultants,
  shifts,
  leaves
}: AnalyticsProps) {
  // Helper to check if a date is in the selected month & year
  const isSelectedPeriod = (dateStr: string) => {
    const [y, m] = dateStr.split('-').map(Number);
    return y === currentYear && (m - 1) === currentMonth;
  };

  // Helper to count approved vacation days for a consultant in the selected period
  const countVacationDays = (consultantId: string) => {
    let days = 0;
    const cLeaves = leaves.filter(l => l.consultantId === consultantId && l.status === 'Approved');

    cLeaves.forEach(l => {
      // Find overlap with selected month/year
      const start = new Date(l.startDate);
      const end = new Date(l.endDate);

      // Loop over every day of the vacation and check if it's in the selected month/year
      let curr = new Date(start);
      while (curr <= end) {
        const currStr = curr.toISOString().split('T')[0];
        if (isSelectedPeriod(currStr)) {
          days++;
        }
        curr.setDate(curr.getDate() + 1);
      }
    });

    return days;
  };

  // Calculate stats for all consultants
  const stats = consultants.map(c => {
    // Total shifts
    const cShifts = shifts.filter(s => s.consultantId === c.id && isSelectedPeriod(s.date));
    const totalShifts = cShifts.length;

    // Weekend shifts (Friday and Saturday strictly)
    const weekendShifts = cShifts.filter(s => {
      const d = new Date(s.date);
      const dayOfWeek = d.getDay(); // 0 = Sunday, ..., 5 = Friday, 6 = Saturday
      return dayOfWeek === 5 || dayOfWeek === 6;
    }).length;

    // Approved vacations
    const vacationDays = countVacationDays(c.id);

    return {
      consultant: c,
      totalShifts,
      weekendShifts,
      vacationDays
    };
  });

  // Sort by total shifts descending (Leaderboard)
  const rankedStats = [...stats].sort((a, b) => b.totalShifts - a.totalShifts);

  const getMonthName = (monthIdx: number) => {
    const months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];
    return months[monthIdx];
  };

  // WhatsApp share implementation
  const handleShareWhatsApp = () => {
    const monthName = getMonthName(currentMonth);
    let text = `*ICU CONSULTANT SCHEDULE & ROTATION METRICS*\n`;
    text += `Period: *${monthName} ${currentYear}*\n\n`;
    text += `------------------------------------\n\n`;

    rankedStats.forEach((stat, idx) => {
      text += `*#${idx + 1} ${stat.consultant.name}* (${stat.consultant.role})\n`;
      text += `  • *Total Calls (Shifts):* ${stat.totalShifts}\n`;
      text += `  • *Weekend Shifts (Fri/Sat):* ${stat.weekendShifts}\n`;
      text += `  • *Approved Vacations:* ${stat.vacationDays} Days\n\n`;
    });

    text += `Generated by ICU Consultant Management System.`;

    const encodedText = encodeURIComponent(text);
    const whatsappUrl = `https://api.whatsapp.com/send?text=${encodedText}`;
    window.open(whatsappUrl, '_blank');
  };

  return (
    <div id="analytics-view" className="space-y-6">
      {/* Ranked Leaderboard */}
      <div className="space-y-4">
        {rankedStats.map((stat, idx) => {
          const rankColors = [
            'text-primary font-bold bg-primary-fixed/50',
            'text-secondary font-bold bg-secondary-fixed/50',
            'text-on-surface-variant font-bold bg-surface-container-high',
            'text-outline font-bold bg-surface-container'
          ];
          const rankColor = rankColors[idx] || 'text-outline bg-surface-container';

          return (
            <div
              key={stat.consultant.id}
              className="consultant-card bg-surface-container-lowest rounded-xl p-4 flex flex-col gap-4 border border-outline-variant/15 shadow-sm"
            >
              <div className="flex items-center gap-4">
                <img
                  src={stat.consultant.avatar}
                  alt={stat.consultant.name}
                  className="w-14 h-14 rounded-full object-cover border-2 border-primary-fixed shadow-sm shrink-0"
                />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between gap-3">
                    <h3 className="font-headline-sm text-headline-sm text-on-surface truncate">
                      {stat.consultant.name}
                    </h3>
                    <span className={`text-[12px] w-6 h-6 flex items-center justify-center rounded-full ${rankColor}`}>
                      #{idx + 1}
                    </span>
                  </div>
                  <p className="text-label-sm text-on-surface-variant font-label-sm uppercase tracking-wider mt-0.5">
                    {stat.consultant.role}
                  </p>
                </div>
              </div>

              {/* Statistics Grid */}
              <div className="grid grid-cols-3 gap-2">
                {/* Total Shifts */}
                <div className="bg-surface-container-low rounded-lg p-2 flex flex-col items-center justify-center border border-outline-variant/5">
                  <span className="text-headline-sm font-headline-sm text-primary">
                    {stat.totalShifts}
                  </span>
                  <span className="text-[9px] uppercase font-bold text-on-surface-variant tracking-wide mt-1">
                    Total Calls
                  </span>
                </div>

                {/* Weekend Shifts */}
                <div className="bg-secondary-container/10 rounded-lg p-2 flex flex-col items-center justify-center border border-secondary-container/20">
                  <span className="text-headline-sm font-headline-sm text-secondary">
                    {stat.weekendShifts}
                  </span>
                  <span className="text-[9px] uppercase font-bold text-on-secondary-container tracking-wide mt-1">
                    Weekends (Fri/Sat)
                  </span>
                </div>

                {/* Approved Vacation */}
                <div className="bg-surface-container-high rounded-lg p-2 flex flex-col items-center justify-center border border-outline-variant/10">
                  <span className="text-headline-sm font-headline-sm text-on-surface">
                    {stat.vacationDays}
                  </span>
                  <span className="text-[9px] uppercase font-bold text-on-surface-variant tracking-wide mt-1">
                    Vacation Days
                  </span>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Share Button */}
      <div className="flex justify-center pt-4">
        <button
          onClick={handleShareWhatsApp}
          className="whatsapp-glow w-full py-4 px-6 rounded-xl flex items-center justify-center gap-3 text-white font-bold active:scale-95 transition-transform duration-150 cursor-pointer text-headline-sm shadow-md"
        >
          <Share2 className="w-5 h-5 text-white" />
          <span>Share via WhatsApp</span>
        </button>
      </div>
    </div>
  );
}
