/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Consultant, Shift, LeaveRequest } from '../types';
import { Calendar, Award, Share2, ShieldAlert } from 'lucide-react';
import { getConsultantColor, getInitials } from '../utils/consultantColors';
import { isWeekendStr, toDateStr } from '../utils/dates';

interface AnalyticsProps {
  currentYear: number;
  currentMonth: number; // 0-indexed
  consultants: Consultant[];
  shifts: Shift[];
  leaves: LeaveRequest[];
}

export default function Analytics({
  currentYear,
  currentMonth,
  consultants,
  shifts,
  leaves
}: AnalyticsProps) {
  // Helper to check if a date is in the selected month & year
  const isSelectedPeriod = (dateStr: string) => {
    const [y, m] = dateStr.split('-').map(Number);
    return y === currentYear && (m - 1) === currentMonth;
  };

  // Helper to count approved vacation days for a consultant in the selected period
  // (on-call preference requests are excluded — they aren't vacations).
  const countVacationDays = (consultantId: string) => {
    let days = 0;
    const cLeaves = leaves.filter(
      l => l.consultantId === consultantId && l.status === 'Approved' && l.kind !== 'OnCall'
    );

    cLeaves.forEach(l => {
      // Iterate day-by-day in local time (no UTC drift).
      const [sy, sm, sd] = l.startDate.split('-').map(Number);
      const [ey, em, ed] = l.endDate.split('-').map(Number);
      const end = new Date(ey, em - 1, ed);
      const curr = new Date(sy, sm - 1, sd);
      while (curr <= end) {
        if (isSelectedPeriod(toDateStr(curr))) days++;
        curr.setDate(curr.getDate() + 1);
      }
    });

    return days;
  };

  // Distinct on-call days = unique dates a consultant has any shift assigned.
  const stats = consultants.map(c => {
    const monthShifts = shifts.filter(s => s.consultantId === c.id && isSelectedPeriod(s.date));
    const allShifts = shifts.filter(s => s.consultantId === c.id);

    const onCallDays = new Set(monthShifts.map(s => s.date)).size;
    const weekendOnCallDays = new Set(monthShifts.filter(s => isWeekendStr(s.date)).map(s => s.date)).size;

    // Cumulative across every month in the data.
    const cumulativeOnCallDays = new Set(allShifts.map(s => s.date)).size;
    const cumulativeWeekendDays = new Set(allShifts.filter(s => isWeekendStr(s.date)).map(s => s.date)).size;

    const vacationDays = countVacationDays(c.id);

    return {
      consultant: c,
      onCallDays,
      weekendOnCallDays,
      cumulativeOnCallDays,
      cumulativeWeekendDays,
      vacationDays
    };
  });

  // Sort by on-call days this month (leaderboard).
  const rankedStats = [...stats].sort((a, b) => b.onCallDays - a.onCallDays);

  // Department cumulative KPIs for the selected month.
  const totalOnCallDays = stats.reduce((sum, s) => sum + s.onCallDays, 0);
  const totalWeekendOnCall = stats.reduce((sum, s) => sum + s.weekendOnCallDays, 0);

  const getMonthName = (monthIdx: number) => {
    const months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];
    return months[monthIdx];
  };

  // WhatsApp share implementation
  const handleShareWhatsApp = () => {
    const monthName = getMonthName(currentMonth);
    let text = `*ICU CONSULTANT SCHEDULE & ROTATION METRICS*\n`;
    text += `Period: *${monthName} ${currentYear}*\n\n`;
    text += `------------------------------------\n\n`;

    text += `*DEPARTMENT TOTAL* — On-Call: ${totalOnCallDays} days · Weekend On-Call: ${totalWeekendOnCall} days\n\n`;

    rankedStats.forEach((stat, idx) => {
      text += `*#${idx + 1} ${stat.consultant.name}* (${stat.consultant.role})\n`;
      text += `  • *On-Call Days:* ${stat.onCallDays}\n`;
      text += `  • *Weekend On-Call:* ${stat.weekendOnCallDays}\n`;
      text += `  • *Approved Vacations:* ${stat.vacationDays} Days\n`;
      text += `  • *Cumulative:* ${stat.cumulativeOnCallDays} on-call · ${stat.cumulativeWeekendDays} weekend\n\n`;
    });

    text += `Generated by ICU Consultant Management System.`;

    const encodedText = encodeURIComponent(text);
    const whatsappUrl = `https://api.whatsapp.com/send?text=${encodedText}`;
    window.open(whatsappUrl, '_blank');
  };

  return (
    <div id="analytics-view" className="space-y-6">
      {/* Cumulative KPI tiles (department total for the selected month) */}
      <div className="grid grid-cols-2 gap-3">
        <div className="bg-primary text-white rounded-xl p-4 shadow-md relative overflow-hidden">
          <div className="relative z-10">
            <p className="text-headline-lg font-headline-lg leading-none">{totalOnCallDays}</p>
            <p className="text-[11px] uppercase font-bold tracking-wide mt-1 opacity-90">Total On-Call Days</p>
          </div>
          <Calendar className="absolute -right-3 -bottom-3 w-20 h-20 opacity-10" />
        </div>
        <div className="bg-secondary text-on-secondary rounded-xl p-4 shadow-md relative overflow-hidden">
          <div className="relative z-10">
            <p className="text-headline-lg font-headline-lg leading-none">{totalWeekendOnCall}</p>
            <p className="text-[11px] uppercase font-bold tracking-wide mt-1 opacity-90">Weekend On-Call Days</p>
          </div>
          <Award className="absolute -right-3 -bottom-3 w-20 h-20 opacity-10" />
        </div>
      </div>

      {/* Ranked Leaderboard */}
      <div className="space-y-4">
        {rankedStats.map((stat, idx) => {
          const rankColors = [
            'text-primary font-bold bg-primary-fixed/50',
            'text-secondary font-bold bg-secondary-fixed/50',
            'text-on-surface-variant font-bold bg-surface-container-high',
            'text-outline font-bold bg-surface-container'
          ];
          const rankColor = rankColors[idx] || 'text-outline bg-surface-container';

          return (
            <div
              key={stat.consultant.id}
              className="consultant-card bg-surface-container-lowest rounded-xl p-4 flex flex-col gap-4 border border-outline-variant/15 shadow-sm"
            >
              <div className="flex items-center gap-4">
                <div
                  className={`w-14 h-14 rounded-full flex items-center justify-center text-body-lg font-bold shadow-sm shrink-0 ${getConsultantColor(consultants, stat.consultant.id).solid}`}
                >
                  {getInitials(stat.consultant.name)}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center justify-between gap-3">
                    <h3 className="font-headline-sm text-headline-sm text-on-surface truncate">
                      {stat.consultant.name}
                    </h3>
                    <span className={`text-[12px] w-6 h-6 flex items-center justify-center rounded-full ${rankColor}`}>
                      #{idx + 1}
                    </span>
                  </div>
                  <p className="text-label-sm text-on-surface-variant font-label-sm uppercase tracking-wider mt-0.5">
                    {stat.consultant.role}
                  </p>
                </div>
              </div>

              {/* Statistics Grid — this month */}
              <div className="grid grid-cols-3 gap-2">
                {/* On-Call Days */}
                <div className="bg-surface-container-low rounded-lg p-2 flex flex-col items-center justify-center border border-outline-variant/5">
                  <span className="text-headline-sm font-headline-sm text-primary">
                    {stat.onCallDays}
                  </span>
                  <span className="text-[9px] uppercase font-bold text-on-surface-variant tracking-wide mt-1 text-center">
                    On-Call Days
                  </span>
                </div>

                {/* Weekend On-Call */}
                <div className="bg-secondary-container/10 rounded-lg p-2 flex flex-col items-center justify-center border border-secondary-container/20">
                  <span className="text-headline-sm font-headline-sm text-secondary">
                    {stat.weekendOnCallDays}
                  </span>
                  <span className="text-[9px] uppercase font-bold text-on-secondary-container tracking-wide mt-1 text-center">
                    Weekend On-Call
                  </span>
                </div>

                {/* Approved Vacation */}
                <div className="bg-surface-container-high rounded-lg p-2 flex flex-col items-center justify-center border border-outline-variant/10">
                  <span className="text-headline-sm font-headline-sm text-on-surface">
                    {stat.vacationDays}
                  </span>
                  <span className="text-[9px] uppercase font-bold text-on-surface-variant tracking-wide mt-1 text-center">
                    Vacation Days
                  </span>
                </div>
              </div>

              {/* Cumulative (all months) */}
              <div className="flex items-center justify-between bg-surface-container-low rounded-lg px-3 py-2 border border-outline-variant/5">
                <span className="text-[10px] uppercase font-bold text-on-surface-variant tracking-wide">
                  Cumulative (all months)
                </span>
                <span className="text-label-sm font-bold text-on-surface">
                  <span className="text-primary">{stat.cumulativeOnCallDays}</span> on-call ·{' '}
                  <span className="text-secondary">{stat.cumulativeWeekendDays}</span> weekend
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Share Button */}
      <div className="flex justify-center pt-4">
        <button
          onClick={handleShareWhatsApp}
          className="whatsapp-glow w-full py-4 px-6 rounded-xl flex items-center justify-center gap-3 text-white font-bold active:scale-95 transition-transform duration-150 cursor-pointer text-headline-sm shadow-md"
        >
          <Share2 className="w-5 h-5 text-white" />
          <span>Share via WhatsApp</span>
        </button>
      </div>
    </div>
  );
}
